<?php

// 应用公共文件
function getMenuList()
{
    $data = \think\Db::table('menu')->select();

//    return $data;
    return array(
        array(
            "f_moduleid" => "1",
            //父id
            "f_parentid" => "0",
            "f_encode" => "SysManage",
            "f_fullname" => "系统管理",
            "f_icon" => "fa fa-desktop",
            "f_urladdress" => null,
            "f_target" => "expand",
            "f_ismenu" => 0,
            "f_allowexpand" => 1,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 1,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => null,
            "f_createuserid" => null,
            "f_createusername" => null,
            "f_modifydate" => "2015-11-17 11:22:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
        array(
            "f_moduleid" => "7ae94059-9aa5-48eb-8330-4e2a6565b193",
            "f_parentid" => "1",
            "f_encode" => "AreaManage",
            "f_fullname" => "欢迎首页",
            "f_icon" => "fa fa-leaf",
            "f_urladdress" => url('index/index_i'),
            "f_target" => "iframe",
            "f_ismenu" => 1,
            "f_allowexpand" => 1,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 1,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => '行政区域管理',
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
        array(
            "f_moduleid" => "231",
            "f_parentid" => "1",
            "f_encode" => "Client_ExpensesType",
            "f_fullname" => "用户管理",
            "f_icon" => "fa fa-tag",
            "f_urladdress" => url('index/user_ctrl'),
            "f_target" => "iframe",
            "f_ismenu" => 1,
            "f_allowexpand" => 0,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 2,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
        array(
            "f_moduleid" => "2311",
            "f_parentid" => "1",
            "f_encode" => "Client_ExpensesType",
            "f_fullname" => "系统管理",
            "f_icon" => "fa fa-tag",
            "f_urladdress" => "/SystemManage/DataItemList/Index?ItemCode=Client_ExpensesType",
            "f_target" => "iframe",
            "f_ismenu" => 3,
            "f_allowexpand" => 0,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 3,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),

        array(
            "f_moduleid" => "23234",
            "f_parentid" => "1",
            "f_encode" => "Client_ExpensesType",
            "f_fullname" => "角色管理",
            "f_icon" => "fa fa-tag",
            "f_urladdress" => url('index/permis_index'),
            "f_target" => "iframe",
            "f_ismenu" => 3,
            "f_allowexpand" => 0,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 3,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
        array(
            "f_moduleid" => "2994",
            "f_parentid" => "1",
            "f_encode" => "Client_ExpensesType",
            "f_fullname" => "权限管理",
            "f_icon" => "fa fa-tag",
            "f_urladdress" => url('index/permis_index'),
            "f_target" => "iframe",
            "f_ismenu" => 3,
            "f_allowexpand" => 0,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 3,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),


        array(
            "f_moduleid" => "32343248932",
            //父id
            "f_parentid" => "0",
            "f_encode" => "SysManage",
            "f_fullname" => "保险管理",
            "f_icon" => "fa fa-desktop",
            "f_urladdress" => null,
            "f_target" => "expand",
            "f_ismenu" => 0,
            "f_allowexpand" => 1,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 1,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => null,
            "f_createuserid" => null,
            "f_createusername" => null,
            "f_modifydate" => "2015-11-17 11:22:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
        array(
            "f_moduleid" => "31232132",
            "f_parentid" => "32343248932",
            "f_encode" => "Client_ExpensesType",
            "f_fullname" => "保险单管理",
            "f_icon" => "fa fa-tag",
            "f_urladdress" => url('index/index2'),
            "f_target" => "iframe",
            "f_ismenu" => 3,
            "f_allowexpand" => 0,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 3,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
        array(
            "f_moduleid" => "2324",
            "f_parentid" => "32343248932",
            "f_encode" => "Client_ExpensesType",
            "f_fullname" => "投保人员管理",
            "f_icon" => "fa fa-tag",
            "f_urladdress" => url('index/index3'),
            "f_target" => "iframe",
            "f_ismenu" => 3,
            "f_allowexpand" => 0,
            "f_ispublic" => 0,
            "f_allowedit" => null,
            "f_allowdelete" => null,
            "f_sortcode" => 3,
            "f_deletemark" => 0,
            "f_enabledmark" => 1,
            "f_description" => null,
            "f_createdate" => "2016-04-20 15:06:10",
            "f_createuserid" => "System",
            "f_createusername" => "超级管理员",
            "f_modifydate" => "2016-04-20 15:06:46",
            "f_modifyuserid" => "System",
            "f_modifyusername" => "超级管理员"
        ),
    );

}

